---
name: Publish Docker images
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    env:
      REPO_URL: ghcr.io
      REPO_PROJECT: sagolubev
    strategy:
      matrix:
        image: [runners]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # login to registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          # set -x
          docker build -t $REPO_URL/$REPO_PROJECT/$IMAGE $IMAGE/.
      
      - name: Tag
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          # set -x
          VERSION=$(cat $IMAGE/VERSION)
          echo $VERSION
          docker tag $REPO_URL/$REPO_PROJECT/$IMAGE:latest $REPO_URL/$REPO_PROJECT/$IMAGE:$VERSION
      
      - name: Push images
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          # set -x
          VERSION=$(cat $IMAGE/VERSION)
          docker push $REPO_URL/$REPO_PROJECT/$IMAGE:latest
          docker push $REPO_URL/$REPO_PROJECT/$IMAGE:$VERSION

